### ISSUE TITLE
[EXPIRED] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [k3rb3ros/three_fizer#2]
Dear Ryan,
Could you be so kind to generate ```.exe``` for the rest of us who use Windows, if possible?

**Comment by k3rb3ros** [comment]
Right now three_fizer relies on the unix/linux device "/dev/random" as a source of randomness for initialization vectors. Windows does not provide you access to randomness through this same method. In order to make three_fizer work (compile and run) on windows the code would have to be re-written to use the Windows Crypto API or include its own cryptographically secure random number generator. These are both quit complicated and I have no immediate plans to add this functionality in the near future sorry :/

**Comment by sergeevabc** [comment]
Ryan, what about [PCG][1]?
It seems to be a great cross-platform alternative to /dev/random.
Let alone it is [small and easily integrated][2] into your project, right?

[1]: http://www.pcg-random.org/
[2]: http://www.pcg-random.org/download.html

**Comment by k3rb3ros** [comment]
I will look into this.

**Comment by sergeevabc** [comment]
> What about PCG?
> I will look into this.

What’s your opinion, Ryan?

**Comment by k3rb3ros** [comment]
PCG seems like a great portable cryptographic random number generator. I have since added it into three_fizer as the source of randomness for cryptographic primitives that need it. [three_fizer pcg support](https://github.com/k3rb3ros/three_fizer/commit/b59af94c8af99cdaaa87565fdb2d6a5aede00157.)

My initial assessment of what would be necessary to get three_fizer running on windows was not complete. There are a few other non Windows portable parts (usage of pthreads and argument parsing code) I forgot about last time that would have to be changed out or re-written to be made Windows compatible. As such even with the change to pcg the project is still not in a state where I can build a Windows binary.

This is a side project and currently I don't have much time to dedicate on it as I am focusing on my career. I may revisit the issue of getting this to compile on windows in the future. At best this would be several months from now.

If you want to fork the project and create a Windows version feel free. But if you are looking for a Windows binary from me its going to be a long time before I can do it.

**Comment by sergeevabc** [comment]
@k3rb3ros, thank you for updating me about the progress, let’s return to this issue in a few weeks then.

**Comment by sergeevabc** [comment]
@k3rb3ros, did you get a chance to look into this more thoroughly?
